.TH "AboutDlg" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AboutDlg \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dlg_about\&.h>\fP
.PP
Inherits \fBDlgAbout\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAboutDlg\fP (wxWindow *parent)"
.br
.ti -1c
.RI "void \fBExchangeData\fP (int inout)"
.br
.ti -1c
.RI "void \fBOnOK\fP (wxCommandEvent &event)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnInitDialog\fP (wxInitDialogEvent &event)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file dlg_about\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AboutDlg::AboutDlg (wxWindow *parent)"
Constructor 
.PP
Definition at line 14 of file dlg_about\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void AboutDlg::ExchangeData (intinout)"

.PP
Definition at line 26 of file dlg_about\&.cpp\&.
.SS "void AboutDlg::OnInitDialog (wxInitDialogEvent &event)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBDlgAbout\fP\&.
.PP
Definition at line 18 of file dlg_about\&.cpp\&.
.SS "void AboutDlg::OnOK (wxCommandEvent &event)"

.PP
Definition at line 59 of file dlg_about\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
