.TH "AboutDlg" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AboutDlg \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dlg_about\&.h>\fP
.PP
Inherits \fBDlgAbout\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAboutDlg\fP (wxWindow *parent)"
.br
.ti -1c
.RI "void \fBExchangeData\fP (int inout)"
.br
.ti -1c
.RI "void \fBOnOK\fP (wxCommandEvent &event)"
.br
.in -1c