.TH "C:/bin/Projects/Radio/fdmdv2/src/detritus/audiostream.h" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/bin/Projects/Radio/fdmdv2/src/detritus/audiostream.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include 'portaudiocpp/PortAudioCpp\&.hxx'\fP
.br
\fC#include <wx/wx\&.h>\fP
.br
\fC#include <wx/thread\&.h>\fP
.br
\fC#include 'libsndfile/include/sndfile\&.h'\fP
.br
\fC#include 'extern/include/portaudio\&.h'\fP
.br
\fC#include 'extern/include/portaudiocpp/PortAudioCpp\&.hxx'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAudioStream\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBNUM_SECONDS\fP = 5"
.br
.ti -1c
.RI "const double \fBSAMPLE_RATE\fP = 44100\&.0"
.br
.ti -1c
.RI "const int \fBFRAMES_PER_BUFFER\fP = 64"
.br
.ti -1c
.RI "const int \fBTABLE_SIZE\fP = 200"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int FRAMES_PER_BUFFER = 64"

.PP
Definition at line 21 of file audiostream\&.h\&.
.SS "const int NUM_SECONDS = 5"

.PP
Definition at line 19 of file audiostream\&.h\&.
.SS "const double SAMPLE_RATE = 44100\&.0"

.PP
Definition at line 20 of file audiostream\&.h\&.
.SS "const int TABLE_SIZE = 200"

.PP
Definition at line 22 of file audiostream\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
