.TH "COMP" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COMP \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <comp\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBreal\fP"
.br
.ti -1c
.RI "float \fBimag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file comp\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float COMP::imag"

.PP
Definition at line 36 of file comp\&.h\&.
.SS "float COMP::real"

.PP
Definition at line 35 of file comp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
