.TH "DlgAbout" 3 "Wed Sep 19 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DlgAbout \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <topFrame\&.h>\fP
.PP
Inherits wxDialog\&.
.PP
Inherited by \fBAboutDlg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDlgAbout\fP (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=_('About FDMDV2'), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(352, 343), long style=wxDEFAULT_DIALOG_STYLE)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnClose\fP (wxCloseEvent &event)"
.br
.ti -1c
.RI "virtual void \fBOnInitDialog\fP (wxInitDialogEvent &event)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "wxStaticBitmap * \fBm_bitmapAbout\fP"
.br
.ti -1c
.RI "wxStaticText * \fBm_staticText1\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl2\fP"
.br
.ti -1c
.RI "wxButton * \fBm_button9\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBDlgAbout\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
