.TH "DlgComPorts" 3 "Tue Sep 11 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DlgComPorts \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <topFrame\&.h>\fP
.PP
Inherits wxDialog\&.
.PP
Inherited by \fBComPortsDlg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDlgComPorts\fP (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=_('Select Com Port'), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(399, 226), long style=wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnListItemSelected\fP (wxListEvent &event)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "wxStaticText * \fBm_staticText8\fP"
.br
.ti -1c
.RI "wxListCtrl * \fBm_listCtrlPortSelect\fP"
.br
.ti -1c
.RI "wxStaticText * \fBm_staticText9\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl10\fP"
.br
.ti -1c
.RI "wxStdDialogButtonSizer * \fBm_sdbSizer3\fP"
.br
.ti -1c
.RI "wxButton * \fBm_sdbSizer3OK\fP"
.br
.ti -1c
.RI "wxButton * \fBm_sdbSizer3Cancel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBDlgComPorts\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
