.TH "DlgOptions" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DlgOptions \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <topFrame\&.h>\fP
.PP
Inherits wxDialog\&.
.PP
Inherited by \fBOptionsDlg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDlgOptions\fP (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=_('Program Options'), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(332, 364), long style=wxDEFAULT_DIALOG_STYLE)"
.br
.ti -1c
.RI "\fB~DlgOptions\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnClose\fP (wxCloseEvent &event)"
.br
.ti -1c
.RI "virtual void \fBOnInitDialog\fP (wxInitDialogEvent &event)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "wxStaticText * \fBm_staticText2\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl3\fP"
.br
.ti -1c
.RI "wxStaticText * \fBm_staticText3\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl4\fP"
.br
.ti -1c
.RI "wxStaticText * \fBm_staticText4\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl5\fP"
.br
.ti -1c
.RI "wxStaticText * \fBm_staticText5\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl6\fP"
.br
.ti -1c
.RI "wxStaticText * \fBm_staticText6\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl7\fP"
.br
.ti -1c
.RI "wxStaticText * \fBm_staticText7\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl8\fP"
.br
.ti -1c
.RI "wxStdDialogButtonSizer * \fBm_sdbSizer4\fP"
.br
.ti -1c
.RI "wxButton * \fBm_sdbSizer4OK\fP"
.br
.ti -1c
.RI "wxButton * \fBm_sdbSizer4Cancel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBDlgOptions\fP 
.PP
Definition at line 235 of file topFrame\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DlgOptions::DlgOptions (wxWindow *parent, wxWindowIDid = \fCwxID_ANY\fP, const wxString &title = \fC_('Program Options')\fP, const wxPoint &pos = \fCwxDefaultPosition\fP, const wxSize &size = \fCwxSize( 332,364 )\fP, longstyle = \fCwxDEFAULT_DIALOG_STYLE\fP)"

.PP
Definition at line 815 of file topFrame\&.cpp\&.
.SS "DlgOptions::~DlgOptions ()"

.PP
Definition at line 898 of file topFrame\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void DlgOptions::OnClose (wxCloseEvent &event)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBOptionsDlg\fP\&.
.PP
Definition at line 257 of file topFrame\&.h\&.
.SS "virtual void DlgOptions::OnInitDialog (wxInitDialogEvent &event)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBOptionsDlg\fP\&.
.PP
Definition at line 258 of file topFrame\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "wxStdDialogButtonSizer* DlgOptions::m_sdbSizer4\fC [protected]\fP"

.PP
Definition at line 252 of file topFrame\&.h\&.
.SS "wxButton* DlgOptions::m_sdbSizer4Cancel\fC [protected]\fP"

.PP
Definition at line 254 of file topFrame\&.h\&.
.SS "wxButton* DlgOptions::m_sdbSizer4OK\fC [protected]\fP"

.PP
Definition at line 253 of file topFrame\&.h\&.
.SS "wxStaticText* DlgOptions::m_staticText2\fC [protected]\fP"

.PP
Definition at line 240 of file topFrame\&.h\&.
.SS "wxStaticText* DlgOptions::m_staticText3\fC [protected]\fP"

.PP
Definition at line 242 of file topFrame\&.h\&.
.SS "wxStaticText* DlgOptions::m_staticText4\fC [protected]\fP"

.PP
Definition at line 244 of file topFrame\&.h\&.
.SS "wxStaticText* DlgOptions::m_staticText5\fC [protected]\fP"

.PP
Definition at line 246 of file topFrame\&.h\&.
.SS "wxStaticText* DlgOptions::m_staticText6\fC [protected]\fP"

.PP
Definition at line 248 of file topFrame\&.h\&.
.SS "wxStaticText* DlgOptions::m_staticText7\fC [protected]\fP"

.PP
Definition at line 250 of file topFrame\&.h\&.
.SS "wxTextCtrl* DlgOptions::m_textCtrl3\fC [protected]\fP"

.PP
Definition at line 241 of file topFrame\&.h\&.
.SS "wxTextCtrl* DlgOptions::m_textCtrl4\fC [protected]\fP"

.PP
Definition at line 243 of file topFrame\&.h\&.
.SS "wxTextCtrl* DlgOptions::m_textCtrl5\fC [protected]\fP"

.PP
Definition at line 245 of file topFrame\&.h\&.
.SS "wxTextCtrl* DlgOptions::m_textCtrl6\fC [protected]\fP"

.PP
Definition at line 247 of file topFrame\&.h\&.
.SS "wxTextCtrl* DlgOptions::m_textCtrl7\fC [protected]\fP"

.PP
Definition at line 249 of file topFrame\&.h\&.
.SS "wxTextCtrl* DlgOptions::m_textCtrl8\fC [protected]\fP"

.PP
Definition at line 251 of file topFrame\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
