.TH "DlgOptions" 3 "Fri Sep 14 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DlgOptions \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <topFrame\&.h>\fP
.PP
Inherits wxDialog\&.
.PP
Inherited by \fBOptionsDlg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDlgOptions\fP (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=_('Program Options'), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(332, 364), long style=wxDEFAULT_DIALOG_STYLE)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnClose\fP (wxCloseEvent &event)"
.br
.ti -1c
.RI "virtual void \fBOnInitDialog\fP (wxInitDialogEvent &event)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "wxStaticText * \fBm_staticText2\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl3\fP"
.br
.ti -1c
.RI "wxStaticText * \fBm_staticText3\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl4\fP"
.br
.ti -1c
.RI "wxStaticText * \fBm_staticText4\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl5\fP"
.br
.ti -1c
.RI "wxStaticText * \fBm_staticText5\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl6\fP"
.br
.ti -1c
.RI "wxStaticText * \fBm_staticText6\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl7\fP"
.br
.ti -1c
.RI "wxStaticText * \fBm_staticText7\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBm_textCtrl8\fP"
.br
.ti -1c
.RI "wxStdDialogButtonSizer * \fBm_sdbSizer4\fP"
.br
.ti -1c
.RI "wxButton * \fBm_sdbSizer4OK\fP"
.br
.ti -1c
.RI "wxButton * \fBm_sdbSizer4Cancel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBDlgOptions\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
