.TH "fdmdv2TopFrame" 3 "Mon Sep 10 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fdmdv2TopFrame \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fdmdv2TopFrame\&.h>\fP
.PP
Inherits \fBTopFrame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfdmdv2TopFrame\fP (wxWindow *parent)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBtopFrame_OnClose\fP (wxCloseEvent &event)"
.br
.ti -1c
.RI "void \fBtopFrame_OnPaint\fP (wxPaintEvent &event)"
.br
.ti -1c
.RI "void \fBtopFrame_OnSize\fP (wxSizeEvent &event)"
.br
.ti -1c
.RI "void \fBtopFrame_OnUpdateUI\fP (wxUpdateUIEvent &event)"
.br
.ti -1c
.RI "void \fBOnOpen\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnOpenUpdateUI\fP (wxUpdateUIEvent &event)"
.br
.ti -1c
.RI "void \fBOnSave\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnSaveUpdateUI\fP (wxUpdateUIEvent &event)"
.br
.ti -1c
.RI "void \fBOnClose\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnCloseUpdateUI\fP (wxUpdateUIEvent &event)"
.br
.ti -1c
.RI "void \fBOnExit\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnCopy\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnCopyUpdateUI\fP (wxUpdateUIEvent &event)"
.br
.ti -1c
.RI "void \fBOnCut\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnCutUpdateUI\fP (wxUpdateUIEvent &event)"
.br
.ti -1c
.RI "void \fBOnPaste\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnPasteUpdateUI\fP (wxUpdateUIEvent &event)"
.br
.ti -1c
.RI "void \fBOnToolsAudio\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnToolsAudioUI\fP (wxUpdateUIEvent &event)"
.br
.ti -1c
.RI "void \fBOnToolsComCfg\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnToolsComCfgUI\fP (wxUpdateUIEvent &event)"
.br
.ti -1c
.RI "void \fBOnToolsOptions\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnToolsOptionsUI\fP (wxUpdateUIEvent &event)"
.br
.ti -1c
.RI "void \fBOnHelpCheckUpdates\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnHelpCheckUpdatesUI\fP (wxUpdateUIEvent &event)"
.br
.ti -1c
.RI "void \fBOnHelpAbout\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnTogBtnRxID\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnTogBtnTxID\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnCmdSliderScroll\fP (wxScrollEvent &event)"
.br
.ti -1c
.RI "void \fBOnSliderScrollBottom\fP (wxScrollEvent &event)"
.br
.ti -1c
.RI "void \fBOnCmdSliderScrollChanged\fP (wxScrollEvent &event)"
.br
.ti -1c
.RI "void \fBOnSliderScrollTop\fP (wxScrollEvent &event)"
.br
.ti -1c
.RI "void \fBOnCheckSQClick\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnTogBtnSplitClick\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnTogBtnAnalogClick\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnTogBtnALCClick\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnTogBtnTXClick\fP (wxCommandEvent &event)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Implementing \fBTopFrame\fP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "fdmdv2TopFrame::fdmdv2TopFrame (wxWindow *parent)"
Constructor 

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
