.TH "C:/bin/Projects/Radio/fdmdv2/src/fdmdv2_pa_wrapper.h" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/bin/Projects/Radio/fdmdv2/src/fdmdv2_pa_wrapper.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'fdmdv2_defines\&.h'\fP
.br
\fC#include 'fdmdv\&.h'\fP
.br
\fC#include 'codec2\&.h'\fP
.br
\fC#include 'portaudio\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPortAudioWrap\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPA_SAMPLE_TYPE\fP   paInt16"
.br
.ti -1c
.RI "#define \fBFRAMES_PER_BUFFER\fP   (64)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef float \fBSAMPLE\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FRAMES_PER_BUFFER   (64)"

.PP
Definition at line 32 of file fdmdv2_pa_wrapper\&.h\&.
.SS "#define PA_SAMPLE_TYPE   paInt16"

.PP
Definition at line 31 of file fdmdv2_pa_wrapper\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef float \fBSAMPLE\fP"

.PP
Definition at line 34 of file fdmdv2_pa_wrapper\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
