.TH "C:/bin/Projects/Radio/fdmdv2/src/fdmdv2_plot.h" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/bin/Projects/Radio/fdmdv2/src/fdmdv2_plot.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/wx\&.h>\fP
.br
\fC#include <wx/aui/auibook\&.h>\fP
.br
\fC#include <wx/rawbmp\&.h>\fP
.br
\fC#include <wx/image\&.h>\fP
.br
\fC#include <wx/dcbuffer\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlotPanel\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_ZOOM\fP   7"
.br
.ti -1c
.RI "#define \fBMAX_BMP_X\fP   (400 * \fBMAX_ZOOM\fP)"
.br
.ti -1c
.RI "#define \fBMAX_BMP_Y\fP   (400 * \fBMAX_ZOOM\fP)"
.br
.ti -1c
.RI "#define \fBDATA_LINE_HEIGHT\fP   10"
.br
.ti -1c
.RI "#define \fBTEXT_BASELINE_OFFSET_Y\fP   -5"
.br
.ti -1c
.RI "#define \fBwxUSE_FILEDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LIBPNG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LIBJPEG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_GIF\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PCX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LIBTIFF\fP   1"
.br
.ti -1c
.RI "#define \fBPLOT_BORDER\fP   3"
.br
.ti -1c
.RI "#define \fBXLEFT_OFFSET\fP   30"
.br
.ti -1c
.RI "#define \fBXLEFT_TEXT_OFFSET\fP   8"
.br
.ti -1c
.RI "#define \fBYBOTTOM_OFFSET\fP   25"
.br
.ti -1c
.RI "#define \fBGRID_INCREMENT\fP   50"
.br
.ti -1c
.RI "#define \fBBLACK_COLOR\fP   wxColor(0x00, 0x00, 0x00)"
.br
.ti -1c
.RI "#define \fBGREY_COLOR\fP   wxColor(0x80, 0x80, 0x80)"
.br
.ti -1c
.RI "#define \fBDARK_GREY_COLOR\fP   wxColor(0x40, 0x40, 0x40)"
.br
.ti -1c
.RI "#define \fBMEDIUM_GREY_COLOR\fP   wxColor(0xC0, 0xC0, 0xC0)"
.br
.ti -1c
.RI "#define \fBLIGHT_GREY_COLOR\fP   wxColor(0xE0, 0xE0, 0xE0)"
.br
.ti -1c
.RI "#define \fBVERY_LTGREY_COLOR\fP   wxColor(0xF8, 0xF8, 0xF8)"
.br
.ti -1c
.RI "#define \fBWHITE_COLOR\fP   wxColor(0xFF, 0xFF, 0xFF)"
.br
.ti -1c
.RI "#define \fBDARK_BLUE_COLOR\fP   wxColor(0x00, 0x00, 0x60)"
.br
.ti -1c
.RI "#define \fBBLUE_COLOR\fP   wxColor(0x00, 0x00, 0xFF)"
.br
.ti -1c
.RI "#define \fBLIGHT_BLUE_COLOR\fP   wxColor(0x80, 0x80, 0xFF)"
.br
.ti -1c
.RI "#define \fBRED_COLOR\fP   wxColor(0xFF, 0x5E, 0x5E)"
.br
.ti -1c
.RI "#define \fBLIGHT_RED_COLOR\fP   wxColor(0xFF, 0xE0, 0xE0)"
.br
.ti -1c
.RI "#define \fBDARK_RED_COLOR\fP   wxColor(0xFF, 0x00, 0x00)"
.br
.ti -1c
.RI "#define \fBPINK_COLOR\fP   wxColor(0xFF, 0x80, 0xFF)"
.br
.ti -1c
.RI "#define \fBLIGHT_GREEN_COLOR\fP   wxColor(0xE3, 0xFF, 0xE0)"
.br
.ti -1c
.RI "#define \fBGREEN_COLOR\fP   wxColor(0x95, 0xFF, 0x8A)"
.br
.ti -1c
.RI "#define \fBDARK_GREEN_COLOR\fP   wxColor(0x20, 0xFF, 0x08)"
.br
.ti -1c
.RI "#define \fBVERY_GREEN_COLOR\fP   wxColor(0x00, 0xFF, 0x00)"
.br
.ti -1c
.RI "#define \fBYELLOW_COLOR\fP   wxColor(0xFF, 0xFF, 0x5E)"
.br
.ti -1c
.RI "#define \fBLIGHT_YELLOW_COLOR\fP   wxColor(0xFF, 0xFF, 0xB5)"
.br
.ti -1c
.RI "#define \fBDARK_YELLOW_COLOR\fP   wxColor(0xFF, 0xFF, 0x08)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLACK_COLOR   wxColor(0x00, 0x00, 0x00)"

.PP
Definition at line 39 of file fdmdv2_plot\&.h\&.
.SS "#define BLUE_COLOR   wxColor(0x00, 0x00, 0xFF)"

.PP
Definition at line 48 of file fdmdv2_plot\&.h\&.
.SS "#define DARK_BLUE_COLOR   wxColor(0x00, 0x00, 0x60)"

.PP
Definition at line 47 of file fdmdv2_plot\&.h\&.
.SS "#define DARK_GREEN_COLOR   wxColor(0x20, 0xFF, 0x08)"

.PP
Definition at line 58 of file fdmdv2_plot\&.h\&.
.SS "#define DARK_GREY_COLOR   wxColor(0x40, 0x40, 0x40)"

.PP
Definition at line 41 of file fdmdv2_plot\&.h\&.
.SS "#define DARK_RED_COLOR   wxColor(0xFF, 0x00, 0x00)"

.PP
Definition at line 53 of file fdmdv2_plot\&.h\&.
.SS "#define DARK_YELLOW_COLOR   wxColor(0xFF, 0xFF, 0x08)"

.PP
Definition at line 63 of file fdmdv2_plot\&.h\&.
.SS "#define DATA_LINE_HEIGHT   10"

.PP
Definition at line 22 of file fdmdv2_plot\&.h\&.
.SS "#define GREEN_COLOR   wxColor(0x95, 0xFF, 0x8A)"

.PP
Definition at line 57 of file fdmdv2_plot\&.h\&.
.SS "#define GREY_COLOR   wxColor(0x80, 0x80, 0x80)"

.PP
Definition at line 40 of file fdmdv2_plot\&.h\&.
.SS "#define GRID_INCREMENT   50"

.PP
Definition at line 37 of file fdmdv2_plot\&.h\&.
.SS "#define LIGHT_BLUE_COLOR   wxColor(0x80, 0x80, 0xFF)"

.PP
Definition at line 49 of file fdmdv2_plot\&.h\&.
.SS "#define LIGHT_GREEN_COLOR   wxColor(0xE3, 0xFF, 0xE0)"

.PP
Definition at line 56 of file fdmdv2_plot\&.h\&.
.SS "#define LIGHT_GREY_COLOR   wxColor(0xE0, 0xE0, 0xE0)"

.PP
Definition at line 43 of file fdmdv2_plot\&.h\&.
.SS "#define LIGHT_RED_COLOR   wxColor(0xFF, 0xE0, 0xE0)"

.PP
Definition at line 52 of file fdmdv2_plot\&.h\&.
.SS "#define LIGHT_YELLOW_COLOR   wxColor(0xFF, 0xFF, 0xB5)"

.PP
Definition at line 62 of file fdmdv2_plot\&.h\&.
.SS "#define MAX_BMP_X   (400 * \fBMAX_ZOOM\fP)"

.PP
Definition at line 20 of file fdmdv2_plot\&.h\&.
.SS "#define MAX_BMP_Y   (400 * \fBMAX_ZOOM\fP)"

.PP
Definition at line 21 of file fdmdv2_plot\&.h\&.
.SS "#define MAX_ZOOM   7"

.PP
Definition at line 19 of file fdmdv2_plot\&.h\&.
.SS "#define MEDIUM_GREY_COLOR   wxColor(0xC0, 0xC0, 0xC0)"

.PP
Definition at line 42 of file fdmdv2_plot\&.h\&.
.SS "#define PINK_COLOR   wxColor(0xFF, 0x80, 0xFF)"

.PP
Definition at line 54 of file fdmdv2_plot\&.h\&.
.SS "#define PLOT_BORDER   3"

.PP
Definition at line 33 of file fdmdv2_plot\&.h\&.
.SS "#define RED_COLOR   wxColor(0xFF, 0x5E, 0x5E)"

.PP
Definition at line 51 of file fdmdv2_plot\&.h\&.
.SS "#define TEXT_BASELINE_OFFSET_Y   -5"

.PP
Definition at line 23 of file fdmdv2_plot\&.h\&.
.SS "#define VERY_GREEN_COLOR   wxColor(0x00, 0xFF, 0x00)"

.PP
Definition at line 59 of file fdmdv2_plot\&.h\&.
.SS "#define VERY_LTGREY_COLOR   wxColor(0xF8, 0xF8, 0xF8)"

.PP
Definition at line 44 of file fdmdv2_plot\&.h\&.
.SS "#define WHITE_COLOR   wxColor(0xFF, 0xFF, 0xFF)"

.PP
Definition at line 45 of file fdmdv2_plot\&.h\&.
.SS "#define wxUSE_FILEDLG   1"

.PP
Definition at line 26 of file fdmdv2_plot\&.h\&.
.SS "#define wxUSE_GIF   1"

.PP
Definition at line 29 of file fdmdv2_plot\&.h\&.
.SS "#define wxUSE_LIBJPEG   1"

.PP
Definition at line 28 of file fdmdv2_plot\&.h\&.
.SS "#define wxUSE_LIBPNG   1"

.PP
Definition at line 27 of file fdmdv2_plot\&.h\&.
.SS "#define wxUSE_LIBTIFF   1"

.PP
Definition at line 31 of file fdmdv2_plot\&.h\&.
.SS "#define wxUSE_PCX   1"

.PP
Definition at line 30 of file fdmdv2_plot\&.h\&.
.SS "#define XLEFT_OFFSET   30"

.PP
Definition at line 34 of file fdmdv2_plot\&.h\&.
.SS "#define XLEFT_TEXT_OFFSET   8"

.PP
Definition at line 35 of file fdmdv2_plot\&.h\&.
.SS "#define YBOTTOM_OFFSET   25"

.PP
Definition at line 36 of file fdmdv2_plot\&.h\&.
.SS "#define YELLOW_COLOR   wxColor(0xFF, 0xFF, 0x5E)"

.PP
Definition at line 61 of file fdmdv2_plot\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
