.TH "C:/bin/Projects/Radio/fdmdv2/src/fdmdv2_main.cpp" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/bin/Projects/Radio/fdmdv2/src/fdmdv2_main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'fdmdv2_main\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBwxUSE_FILEDLG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LIBPNG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LIBJPEG\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_GIF\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_PCX\fP   1"
.br
.ti -1c
.RI "#define \fBwxUSE_LIBTIFF\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIMPLEMENT_APP\fP (\fBMainApp\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct CODEC2 * \fBg_pCodec2\fP"
.br
.ti -1c
.RI "struct FDMDV * \fBg_pFDMDV\fP"
.br
.ti -1c
.RI "int \fBg_nRxIn\fP = FDMDV_NOM_SAMPLES_PER_FRAME"
.br
.ti -1c
.RI "float \fBg_Ts\fP = 0\&.0"
.br
.ti -1c
.RI "short \fBg_RxInBuf\fP [2 *FDMDV_NOM_SAMPLES_PER_FRAME]"
.br
.ti -1c
.RI "short * \fBg_pRxOutBuf\fP"
.br
.ti -1c
.RI "int \fBg_nInputBuf\fP = 0"
.br
.ti -1c
.RI "short \fBg_TxInBuf\fP [2 *FDMDV_NOM_SAMPLES_PER_FRAME]"
.br
.ti -1c
.RI "short * \fBg_pTxOutBuf\fP"
.br
.ti -1c
.RI "int \fBg_nOutputBuf\fP = 0"
.br
.ti -1c
.RI "int \fBg_CodecBits\fP [2 *FDMDV_BITS_PER_FRAME]"
.br
.ti -1c
.RI "int \fBg_State\fP = 0"
.br
.ti -1c
.RI "float \fBg_avmag\fP [\fBFDMDV_NSPEC\fP]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define wxUSE_FILEDLG   1"

.PP
Definition at line 27 of file fdmdv2_main\&.cpp\&.
.SS "#define wxUSE_GIF   1"

.PP
Definition at line 30 of file fdmdv2_main\&.cpp\&.
.SS "#define wxUSE_LIBJPEG   1"

.PP
Definition at line 29 of file fdmdv2_main\&.cpp\&.
.SS "#define wxUSE_LIBPNG   1"

.PP
Definition at line 28 of file fdmdv2_main\&.cpp\&.
.SS "#define wxUSE_LIBTIFF   1"

.PP
Definition at line 32 of file fdmdv2_main\&.cpp\&.
.SS "#define wxUSE_PCX   1"

.PP
Definition at line 31 of file fdmdv2_main\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "IMPLEMENT_APP (\fBMainApp\fP)"

.SH "Variable Documentation"
.PP 
.SS "float g_avmag[\fBFDMDV_NSPEC\fP]"

.PP
Definition at line 849 of file fdmdv2_main\&.cpp\&.
.SS "int g_CodecBits[2 *FDMDV_BITS_PER_FRAME]"

.PP
Definition at line 846 of file fdmdv2_main\&.cpp\&.
.SS "int g_nInputBuf = 0"

.PP
Definition at line 839 of file fdmdv2_main\&.cpp\&.
.SS "int g_nOutputBuf = 0"

.PP
Definition at line 843 of file fdmdv2_main\&.cpp\&.
.SS "int g_nRxIn = FDMDV_NOM_SAMPLES_PER_FRAME"

.PP
Definition at line 834 of file fdmdv2_main\&.cpp\&.
.SS "struct CODEC2* g_pCodec2"

.PP
Definition at line 756 of file fdmdv2_main\&.cpp\&.
.SS "struct FDMDV* g_pFDMDV"

.PP
Definition at line 757 of file fdmdv2_main\&.cpp\&.
.SS "short* g_pRxOutBuf"

.PP
Definition at line 838 of file fdmdv2_main\&.cpp\&.
.SS "short* g_pTxOutBuf"

.PP
Definition at line 842 of file fdmdv2_main\&.cpp\&.
.SS "short g_RxInBuf[2 *FDMDV_NOM_SAMPLES_PER_FRAME]"

.PP
Definition at line 837 of file fdmdv2_main\&.cpp\&.
.SS "int g_State = 0"

.PP
Definition at line 847 of file fdmdv2_main\&.cpp\&.
.SS "float g_Ts = 0\&.0"

.PP
Definition at line 835 of file fdmdv2_main\&.cpp\&.
.SS "short g_TxInBuf[2 *FDMDV_NOM_SAMPLES_PER_FRAME]"

.PP
Definition at line 841 of file fdmdv2_main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
