.TH "C:/bin/Projects/Radio/fdmdv2/src/fdmdv2_plot_spectrum.cpp" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/bin/Projects/Radio/fdmdv2/src/fdmdv2_plot_spectrum.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'wx/wx\&.h'\fP
.br
\fC#include 'fdmdv2_main\&.h'\fP
.br
\fC#include 'fdmdv2_plot_spectrum\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBg_avmag\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "float g_avmag[]"

.PP
Definition at line 849 of file fdmdv2_main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
