.TH "Fdmdv2ThreadAudio" 3 "Tue Sep 11 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fdmdv2ThreadAudio \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits wxThread\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void * \fBEntry\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDelete\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnExit\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnKill\fP ()"
.br
.ti -1c
.RI "virtual bool \fBTestDestroy\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
