.TH "C:/bin/Projects/Radio/fdmdv2/src/fdmdv2_plot_waterfall.h" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/bin/Projects/Radio/fdmdv2/src/fdmdv2_plot_waterfall.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'fdmdv2_plot\&.h'\fP
.br
\fC#include 'fdmdv2_defines\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlotWaterfall\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
