.TH "C:/bin/Projects/Radio/fdmdv2/src/fdmdv2_plot_waterfall.cpp" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/bin/Projects/Radio/fdmdv2/src/fdmdv2_plot_waterfall.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'wx/wx\&.h'\fP
.br
\fC#include 'fdmdv2_main\&.h'\fP
.br
\fC#include 'fdmdv2_plot_waterfall\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPLOT_BOTTOM\fP   0"
.br
.ti -1c
.RI "#define \fBPLOT_TOP\fP   1"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBg_avmag\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PLOT_BOTTOM   0"

.PP
Definition at line 148 of file fdmdv2_plot_waterfall\&.cpp\&.
.SS "#define PLOT_TOP   1"

.PP
Definition at line 149 of file fdmdv2_plot_waterfall\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "float g_avmag[]"

.PP
Definition at line 849 of file fdmdv2_main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
