.TH "MainApp" 3 "Wed Sep 19 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainApp \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits wxApp\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBOnInit\fP ()"
.br
.ti -1c
.RI "virtual int \fBOnExit\fP ()"
.br
.ti -1c
.RI "bool \fBloadConfig\fP ()"
.br
.ti -1c
.RI "bool \fBsaveConfig\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wxString \fBm_strVendName\fP"
.br
.ti -1c
.RI "wxString \fBm_StrAppName\fP"
.br
.ti -1c
.RI "wxRadioButton \fBm_radioBtnPortAudio\fP"
.br
.ti -1c
.RI "wxRadioButton \fBm_radioBtnFileOnly\fP"
.br
.ti -1c
.RI "wxString \fBm_textNumChOut\fP"
.br
.ti -1c
.RI "wxString \fBm_textNumChIn\fP"
.br
.ti -1c
.RI "wxString \fBm_strRxInAudio\fP"
.br
.ti -1c
.RI "wxString \fBm_strRxOutAudio\fP"
.br
.ti -1c
.RI "wxString \fBm_textVoiceInput\fP"
.br
.ti -1c
.RI "wxString \fBm_textVoiceOutput\fP"
.br
.ti -1c
.RI "wxString \fBm_strSampleRate\fP"
.br
.ti -1c
.RI "wxString \fBm_strBitrate\fP"
.br
.ti -1c
.RI "wxString \fBm_strRigCtrlPort\fP"
.br
.ti -1c
.RI "wxString \fBm_strRigCtrlBaud\fP"
.br
.ti -1c
.RI "wxString \fBm_strRigCtrlDatabits\fP"
.br
.ti -1c
.RI "wxString \fBm_strRigCtrlStopbits\fP"
.br
.ti -1c
.RI "wxString \fBm_strRigCtrlParity\fP"
.br
.ti -1c
.RI "wxRect \fBm_rTopWindow\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
