.TH "MyFrame" 3 "Tue Sep 11 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyFrame \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits wxFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDoStartThread\fP ()"
.br
.ti -1c
.RI "void \fBDoPauseThread\fP ()"
.br
.ti -1c
.RI "void \fBDoResumeThread\fP ()"
.br
.ti -1c
.RI "void \fBOnThreadUpdate\fP (wxThreadEvent &)"
.br
.ti -1c
.RI "void \fBOnThreadCompletion\fP (wxThreadEvent &)"
.br
.ti -1c
.RI "void \fBOnClose\fP (wxCloseEvent &)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBwxDECLARE_EVENT_TABLE\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBMyThread\fP * \fBm_pThread\fP"
.br
.ti -1c
.RI "wxCriticalSection \fBm_pThreadCS\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
