.TH "MyThread" 3 "Mon Sep 10 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyThread \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits wxThread\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyThread\fP (\fBMyFrame\fP *handler)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual ExitCode \fBEntry\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBMyFrame\fP * \fBm_pHandler\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
