.TH "OptionsDlg" 3 "Wed Sep 19 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptionsDlg \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDlgOptions\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionsDlg\fP (wxWindow *parent)"
.br
.ti -1c
.RI "void \fBExchangeData\fP (int inout)"
.br
.ti -1c
.RI "void \fBOnCancel\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnOK\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnApply\fP (wxCommandEvent &event)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnClose\fP (wxCloseEvent &event)"
.br
.ti -1c
.RI "void \fBOnInitDialog\fP (wxInitDialogEvent &event)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OptionsDlg::OptionsDlg (wxWindow *parent)"
Constructor 

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
