.TH "paCallBackData" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
paCallBackData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fdmdv2_main\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPlotSpectrum\fP * \fBpSPPanel\fP"
.br
.ti -1c
.RI "\fBPlotWaterfall\fP * \fBpWFPanel\fP"
.br
.ti -1c
.RI "float \fBin48k\fP [FDMDV_OS_TAPS+\fBN48\fP]"
.br
.ti -1c
.RI "float \fBin8k\fP [\fBMEM8\fP+\fBN8\fP]"
.br
.ti -1c
.RI "struct FIFO * \fBinfifo\fP"
.br
.ti -1c
.RI "struct FIFO * \fBoutfifo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 116 of file fdmdv2_main\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float paCallBackData::in48k[FDMDV_OS_TAPS+\fBN48\fP]"

.PP
Definition at line 121 of file fdmdv2_main\&.h\&.
.SS "float paCallBackData::in8k[\fBMEM8\fP+\fBN8\fP]"

.PP
Definition at line 122 of file fdmdv2_main\&.h\&.
.SS "struct FIFO* paCallBackData::infifo"

.PP
Definition at line 123 of file fdmdv2_main\&.h\&.
.SS "struct FIFO* paCallBackData::outfifo"

.PP
Definition at line 124 of file fdmdv2_main\&.h\&.
.SS "\fBPlotSpectrum\fP* paCallBackData::pSPPanel"

.PP
Definition at line 118 of file fdmdv2_main\&.h\&.
.SS "\fBPlotWaterfall\fP* paCallBackData::pWFPanel"

.PP
Definition at line 119 of file fdmdv2_main\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
