.TH "paCallBackData" 3 "Fri Sep 14 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
paCallBackData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBin48k\fP [FDMDV_OS_TAPS+N48]"
.br
.ti -1c
.RI "float \fBin8k\fP [MEM8+N8]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
