.TH "PlotWaterfall" 3 "Tue Sep 11 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlotWaterfall \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPlotPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlotWaterfall\fP (wxFrame *parent)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "unsigned \fBheatmap\fP (float val, float min, float max)"
.br
.ti -1c
.RI "void \fBOnPaint\fP (wxPaintEvent &evt)"
.br
.ti -1c
.RI "void \fBOnSize\fP (wxSizeEvent &event)"
.br
.ti -1c
.RI "void \fBOnShow\fP (wxShowEvent &event)"
.br
.ti -1c
.RI "void \fBdrawGraticule\fP (wxAutoBufferedPaintDC &dc)"
.br
.ti -1c
.RI "void \fBdraw\fP (wxAutoBufferedPaintDC &dc)"
.br
.ti -1c
.RI "void \fBplotData\fP (wxAutoBufferedPaintDC &dc)"
.br
.ti -1c
.RI "void \fBplotPixelData\fP (wxAutoBufferedPaintDC &dc)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBm_heatmap_lut\fP [256]"
.br
.ti -1c
.RI "int \fBm_greyscale\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
