.TH "PlotScatter" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlotScatter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fdmdv2_plot_scatter\&.h>\fP
.PP
Inherits \fBPlotPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlotScatter\fP (wxFrame *parent)"
.br
.ti -1c
.RI "\fB~PlotScatter\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBdraw\fP (wxAutoBufferedPaintDC &dc)"
.br
.ti -1c
.RI "void \fBadd_new_samples\fP (\fBCOMP\fP samples[])"
.br
.ti -1c
.RI "void \fBOnPaint\fP (wxPaintEvent &event)"
.br
.ti -1c
.RI "void \fBOnSize\fP (wxSizeEvent &event)"
.br
.ti -1c
.RI "void \fBOnShow\fP (wxShowEvent &event)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCOMP\fP \fBm_mem\fP [\fBSCATTER_MEM\fP]"
.br
.ti -1c
.RI "\fBCOMP\fP \fBm_new_samples\fP [FDMDV_NSYM]"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 35 of file fdmdv2_plot_scatter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlotScatter::PlotScatter (wxFrame *parent)"

.PP
Definition at line 43 of file fdmdv2_plot_scatter\&.cpp\&.
.SS "PlotScatter::~PlotScatter ()\fC [inline]\fP"

.PP
Definition at line 39 of file fdmdv2_plot_scatter\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void PlotScatter::add_new_samples (\fBCOMP\fPsamples[])\fC [protected]\fP"

.PP
Definition at line 124 of file fdmdv2_plot_scatter\&.cpp\&.
.SS "void PlotScatter::draw (wxAutoBufferedPaintDC &dc)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBPlotPanel\fP\&.
.PP
Definition at line 64 of file fdmdv2_plot_scatter\&.cpp\&.
.SS "void PlotScatter::OnPaint (wxPaintEvent &event)\fC [protected]\fP"

.PP
Definition at line 137 of file fdmdv2_plot_scatter\&.cpp\&.
.SS "void PlotScatter::OnShow (wxShowEvent &event)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBPlotPanel\fP\&.
.PP
Definition at line 155 of file fdmdv2_plot_scatter\&.cpp\&.
.SS "void PlotScatter::OnSize (wxSizeEvent &event)\fC [protected]\fP"

.PP
Definition at line 146 of file fdmdv2_plot_scatter\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCOMP\fP PlotScatter::m_mem[\fBSCATTER_MEM\fP]\fC [protected]\fP"

.PP
Definition at line 39 of file fdmdv2_plot_scatter\&.h\&.
.SS "\fBCOMP\fP PlotScatter::m_new_samples[FDMDV_NSYM]\fC [protected]\fP"

.PP
Definition at line 43 of file fdmdv2_plot_scatter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
