.TH "PlotSpectrum" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlotSpectrum \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fdmdv2_plot_spectrum\&.h>\fP
.PP
Inherits \fBPlotPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlotSpectrum\fP (wxFrame *parent)"
.br
.ti -1c
.RI "\fB~PlotSpectrum\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPaint\fP (wxPaintEvent &event)"
.br
.ti -1c
.RI "void \fBOnSize\fP (wxSizeEvent &event)"
.br
.ti -1c
.RI "void \fBOnShow\fP (wxShowEvent &event)"
.br
.ti -1c
.RI "void \fBdrawGraticule\fP (wxAutoBufferedPaintDC &dc)"
.br
.ti -1c
.RI "void \fBdraw\fP (wxAutoBufferedPaintDC &dc)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 34 of file fdmdv2_plot_spectrum\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlotSpectrum::PlotSpectrum (wxFrame *parent)"

.PP
Definition at line 52 of file fdmdv2_plot_spectrum\&.cpp\&.
.SS "PlotSpectrum::~PlotSpectrum ()"

.PP
Definition at line 65 of file fdmdv2_plot_spectrum\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void PlotSpectrum::draw (wxAutoBufferedPaintDC &dc)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBPlotPanel\fP\&.
.PP
Definition at line 72 of file fdmdv2_plot_spectrum\&.cpp\&.
.SS "void PlotSpectrum::drawGraticule (wxAutoBufferedPaintDC &dc)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBPlotPanel\fP\&.
.PP
Definition at line 131 of file fdmdv2_plot_spectrum\&.cpp\&.
.SS "void PlotSpectrum::OnPaint (wxPaintEvent &event)\fC [protected]\fP"

.PP
Definition at line 179 of file fdmdv2_plot_spectrum\&.cpp\&.
.SS "void PlotSpectrum::OnShow (wxShowEvent &event)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBPlotPanel\fP\&.
.PP
Definition at line 188 of file fdmdv2_plot_spectrum\&.cpp\&.
.SS "void PlotSpectrum::OnSize (wxSizeEvent &event)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
