.TH "PortAudioWrap" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PortAudioWrap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fdmdv2_pa_wrapper\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPortAudioWrap\fP ()"
.br
.ti -1c
.RI "\fB~PortAudioWrap\fP ()"
.br
.ti -1c
.RI "void \fBaverageData\fP (float mag_dB[])"
.br
.ti -1c
.RI "PaDeviceIndex \fBgetDefaultInputDevice\fP ()"
.br
.ti -1c
.RI "PaDeviceIndex \fBgetDefaultOutputDevice\fP ()"
.br
.ti -1c
.RI "PaStreamParameters * \fBgetDeviceInfo\fP (PaDeviceIndex idx)"
.br
.ti -1c
.RI "PaError \fBsetFramesPerBuffer\fP (unsigned long size)"
.br
.ti -1c
.RI "PaError \fBsetSampleRate\fP (unsigned long size)"
.br
.ti -1c
.RI "PaError \fBsetStreamFlags\fP (PaStreamFlags flags)"
.br
.ti -1c
.RI "PaError \fBsetCallback\fP (PaStreamCallback *m_pStreamCallback)"
.br
.ti -1c
.RI "PaError \fBsetStreamCallback\fP (PaStream *stream, PaStreamCallback *callback)"
.br
.ti -1c
.RI "PaError \fBsetStreamFinishedCallback\fP (PaStream *stream, PaStreamFinishedCallback *m_pStreamFinishedCallback)"
.br
.ti -1c
.RI "void \fBsetInputBuffer\fP (const PaStreamParameters &inputBuffer)"
.br
.ti -1c
.RI "PaError \fBsetInputDevice\fP (PaDeviceIndex dev)"
.br
.ti -1c
.RI "PaError \fBsetInputChannelCount\fP (int count)"
.br
.ti -1c
.RI "int \fBgetInputChannelCount\fP ()"
.br
.ti -1c
.RI "PaError \fBsetInputSampleFormat\fP (PaSampleFormat format)"
.br
.ti -1c
.RI "PaError \fBsetInputSampleRate\fP (PaSampleFormat format)"
.br
.ti -1c
.RI "PaError \fBsetInputLatency\fP (PaTime latency)"
.br
.ti -1c
.RI "void \fBsetInputHostApiStreamInfo\fP (void *info=NULL)"
.br
.ti -1c
.RI "PaTime \fBgetInputDefaultLowLatency\fP ()"
.br
.ti -1c
.RI "const char * \fBgetDeviceName\fP (PaDeviceIndex dev)"
.br
.ti -1c
.RI "PaError \fBsetOutputDevice\fP (PaDeviceIndex dev)"
.br
.ti -1c
.RI "PaError \fBsetOutputChannelCount\fP (int count)"
.br
.ti -1c
.RI "const int \fBgetOutputChannelCount\fP ()"
.br
.ti -1c
.RI "PaError \fBsetOutputSampleFormat\fP (PaSampleFormat format)"
.br
.ti -1c
.RI "PaError \fBsetOutputLatency\fP (PaTime latency)"
.br
.ti -1c
.RI "void \fBsetOutputHostApiStreamInfo\fP (void *info=NULL)"
.br
.ti -1c
.RI "PaTime \fBgetOutputDefaultLowLatency\fP ()"
.br
.ti -1c
.RI "void \fBsetFdmdvState\fP (FDMDV *fdmdv_state)"
.br
.ti -1c
.RI "void \fBsetOutputBuffer\fP (const PaStreamParameters &outputBuffer)"
.br
.ti -1c
.RI "void \fBsetTimeInfo\fP (PaStreamCallbackTimeInfo *timeInfo)"
.br
.ti -1c
.RI "void \fBsetUserData\fP (void *userData)"
.br
.ti -1c
.RI "unsigned long \fBgetFramesPerBuffer\fP () const "
.br
.ti -1c
.RI "const PaStreamParameters & \fBgetInputBuffer\fP () const "
.br
.ti -1c
.RI "const PaStreamParameters & \fBgetOutputBuffer\fP () const "
.br
.ti -1c
.RI "const PaStreamCallbackFlags & \fBgetStatusFlags\fP () const "
.br
.ti -1c
.RI "FDMDV * \fBgetFdmdvState\fP ()"
.br
.ti -1c
.RI "int \fBgetSamplerate\fP () const "
.br
.ti -1c
.RI "PaStream * \fBgetStream\fP ()"
.br
.ti -1c
.RI "void * \fBgetUserData\fP ()"
.br
.ti -1c
.RI "bool \fBgetDataAvail\fP ()"
.br
.ti -1c
.RI "PaError \fBstreamStart\fP ()"
.br
.ti -1c
.RI "PaError \fBstreamClose\fP ()"
.br
.ti -1c
.RI "PaError \fBstreamOpen\fP ()"
.br
.ti -1c
.RI "void \fBterminate\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBabort\fP ()"
.br
.ti -1c
.RI "bool \fBisOpen\fP () const "
.br
.ti -1c
.RI "bool \fBisStopped\fP () const "
.br
.ti -1c
.RI "bool \fBisActive\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file fdmdv2_pa_wrapper\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PortAudioWrap::PortAudioWrap ()"

.PP
Definition at line 29 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PortAudioWrap::~PortAudioWrap ()"

.PP
Definition at line 47 of file fdmdv2_pa_wrapper\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void PortAudioWrap::abort ()"

.PP
Definition at line 115 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "void PortAudioWrap::averageData (floatmag_dB[])"

.SS "bool PortAudioWrap::getDataAvail ()\fC [inline]\fP"

.PP
Definition at line 106 of file fdmdv2_pa_wrapper\&.h\&.
.SS "PaDeviceIndex PortAudioWrap::getDefaultInputDevice ()"

.PP
Definition at line 149 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaDeviceIndex PortAudioWrap::getDefaultOutputDevice ()"

.PP
Definition at line 157 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaStreamParameters* PortAudioWrap::getDeviceInfo (PaDeviceIndexidx)"

.SS "const char * PortAudioWrap::getDeviceName (PaDeviceIndexdev)"

.PP
Definition at line 233 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "FDMDV* PortAudioWrap::getFdmdvState ()\fC [inline]\fP"

.PP
Definition at line 102 of file fdmdv2_pa_wrapper\&.h\&.
.SS "unsigned long PortAudioWrap::getFramesPerBuffer () const\fC [inline]\fP"

.PP
Definition at line 97 of file fdmdv2_pa_wrapper\&.h\&.
.SS "const PaStreamParameters& PortAudioWrap::getInputBuffer () const\fC [inline]\fP"

.PP
Definition at line 98 of file fdmdv2_pa_wrapper\&.h\&.
.SS "PaError PortAudioWrap::getInputChannelCount ()"

.PP
Definition at line 174 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaTime PortAudioWrap::getInputDefaultLowLatency ()"

.PP
Definition at line 208 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "const PaStreamParameters& PortAudioWrap::getOutputBuffer () const\fC [inline]\fP"

.PP
Definition at line 99 of file fdmdv2_pa_wrapper\&.h\&.
.SS "const int PortAudioWrap::getOutputChannelCount ()"

.PP
Definition at line 225 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaTime PortAudioWrap::getOutputDefaultLowLatency ()"

.PP
Definition at line 269 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "int PortAudioWrap::getSamplerate () const\fC [inline]\fP"

.PP
Definition at line 103 of file fdmdv2_pa_wrapper\&.h\&.
.SS "const PaStreamCallbackFlags& PortAudioWrap::getStatusFlags () const\fC [inline]\fP"

.PP
Definition at line 100 of file fdmdv2_pa_wrapper\&.h\&.
.SS "PaStream* PortAudioWrap::getStream ()\fC [inline]\fP"

.PP
Definition at line 104 of file fdmdv2_pa_wrapper\&.h\&.
.SS "void* PortAudioWrap::getUserData ()\fC [inline]\fP"

.PP
Definition at line 105 of file fdmdv2_pa_wrapper\&.h\&.
.SS "bool PortAudioWrap::isActive () const"

.PP
Definition at line 132 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "bool PortAudioWrap::isOpen () const"

.PP
Definition at line 141 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "bool PortAudioWrap::isStopped () const"

.PP
Definition at line 123 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::setCallback (PaStreamCallback *m_pStreamCallback)"

.PP
Definition at line 322 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "void PortAudioWrap::setFdmdvState (FDMDV *fdmdv_state)\fC [inline]\fP"

.PP
Definition at line 93 of file fdmdv2_pa_wrapper\&.h\&.
.SS "PaError PortAudioWrap::setFramesPerBuffer (unsigned longsize)"

.PP
Definition at line 277 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "void PortAudioWrap::setInputBuffer (const PaStreamParameters &inputBuffer)\fC [inline]\fP"

.PP
Definition at line 74 of file fdmdv2_pa_wrapper\&.h\&.
.SS "PaError PortAudioWrap::setInputChannelCount (intcount)"

.PP
Definition at line 165 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::setInputDevice (PaDeviceIndexdev)"

.PP
Definition at line 304 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "void PortAudioWrap::setInputHostApiStreamInfo (void *info = \fCNULL\fP)"

.PP
Definition at line 200 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::setInputLatency (PaTimelatency)"

.PP
Definition at line 191 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::setInputSampleFormat (PaSampleFormatformat)"

.PP
Definition at line 182 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::setInputSampleRate (PaSampleFormatformat)"

.SS "void PortAudioWrap::setOutputBuffer (const PaStreamParameters &outputBuffer)\fC [inline]\fP"

.PP
Definition at line 94 of file fdmdv2_pa_wrapper\&.h\&.
.SS "PaError PortAudioWrap::setOutputChannelCount (intcount)"

.PP
Definition at line 216 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::setOutputDevice (PaDeviceIndexdev)"

.PP
Definition at line 313 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "void PortAudioWrap::setOutputHostApiStreamInfo (void *info = \fCNULL\fP)"

.PP
Definition at line 261 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::setOutputLatency (PaTimelatency)"

.PP
Definition at line 252 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::setOutputSampleFormat (PaSampleFormatformat)"

.PP
Definition at line 243 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::setSampleRate (unsigned longsize)"

.PP
Definition at line 286 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::setStreamCallback (PaStream *stream, PaStreamCallback *callback)\fC [inline]\fP"

.PP
Definition at line 71 of file fdmdv2_pa_wrapper\&.h\&.
.SS "PaError PortAudioWrap::setStreamFinishedCallback (PaStream *stream, PaStreamFinishedCallback *m_pStreamFinishedCallback)"

.SS "PaError PortAudioWrap::setStreamFlags (PaStreamFlagsflags)"

.PP
Definition at line 295 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "void PortAudioWrap::setTimeInfo (PaStreamCallbackTimeInfo *timeInfo)\fC [inline]\fP"

.PP
Definition at line 95 of file fdmdv2_pa_wrapper\&.h\&.
.SS "void PortAudioWrap::setUserData (void *userData)\fC [inline]\fP"

.PP
Definition at line 96 of file fdmdv2_pa_wrapper\&.h\&.
.SS "void PortAudioWrap::stop ()"

.PP
Definition at line 107 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::streamClose ()"

.PP
Definition at line 79 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::streamOpen ()"

.PP
Definition at line 54 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "PaError PortAudioWrap::streamStart ()"

.PP
Definition at line 71 of file fdmdv2_pa_wrapper\&.cpp\&.
.SS "void PortAudioWrap::terminate ()"

.PP
Definition at line 95 of file fdmdv2_pa_wrapper\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
