.TH "C:/bin/Projects/Radio/fdmdv2/src/detritus/thread_audio.cpp" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/bin/Projects/Radio/fdmdv2/src/detritus/thread_audio.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'thread_audio\&.h'\fP
.br
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'extern/include/portaudio\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwxDECLARE_EVENT\fP (wxEVT_COMMAND_AUDIOTHREAD_COMPLETED, wxThreadEvent)"
.br
.ti -1c
.RI "\fBwxDECLARE_EVENT\fP (wxEVT_COMMAND_AUDIOTHREAD_UPDATE, wxThreadEvent)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "wxDECLARE_EVENT (wxEVT_COMMAND_AUDIOTHREAD_COMPLETED, wxThreadEvent)"

.SS "wxDECLARE_EVENT (wxEVT_COMMAND_AUDIOTHREAD_UPDATE, wxThreadEvent)"

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
