.TH "topFrame.DlgComPorts" 3 "Tue Sep 11 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
topFrame.DlgComPorts \- 
.PP
Class \fBDlgComPorts\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Dialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__del__\fP"
.br
.ti -1c
.RI "def \fBOnListItemSelected\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBm_staticText8\fP"
.br
.ti -1c
.RI "\fBm_listCtrlPortSelect\fP"
.br
.ti -1c
.RI "\fBm_staticText9\fP"
.br
.ti -1c
.RI "\fBm_textCtrl10\fP"
.br
.ti -1c
.RI "\fBm_sdbSizer3OK\fP"
.br
.ti -1c
.RI "\fBm_sdbSizer3Cancel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBDlgComPorts\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
