.TH "topFrame.TopFrame" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
topFrame.TopFrame \- 
.PP
Class \fBTopFrame\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Frame, and Frame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__del__\fP"
.br
.ti -1c
.RI "def \fBtopFrame_OnClose\fP"
.br
.ti -1c
.RI "def \fBtopFrame_OnPaint\fP"
.br
.ti -1c
.RI "def \fBtopFrame_OnSize\fP"
.br
.ti -1c
.RI "def \fBtopFrame_OnUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnOpen\fP"
.br
.ti -1c
.RI "def \fBOnOpenUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnSave\fP"
.br
.ti -1c
.RI "def \fBOnSaveUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnClose\fP"
.br
.ti -1c
.RI "def \fBOnCloseUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnExit\fP"
.br
.ti -1c
.RI "def \fBOnCopy\fP"
.br
.ti -1c
.RI "def \fBOnCopyUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnCut\fP"
.br
.ti -1c
.RI "def \fBOnCutUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnPaste\fP"
.br
.ti -1c
.RI "def \fBOnPasteUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnToolsAudio\fP"
.br
.ti -1c
.RI "def \fBOnToolsAudioUI\fP"
.br
.ti -1c
.RI "def \fBOnToolsComCfg\fP"
.br
.ti -1c
.RI "def \fBOnToolsComCfgUI\fP"
.br
.ti -1c
.RI "def \fBOnToolsOptions\fP"
.br
.ti -1c
.RI "def \fBOnToolsOptionsUI\fP"
.br
.ti -1c
.RI "def \fBOnCaptureRxStream\fP"
.br
.ti -1c
.RI "def \fBOnCaptureTxStream\fP"
.br
.ti -1c
.RI "def \fBOnPlayAudioFile\fP"
.br
.ti -1c
.RI "def \fBOnHelpCheckUpdates\fP"
.br
.ti -1c
.RI "def \fBOnHelpCheckUpdatesUI\fP"
.br
.ti -1c
.RI "def \fBOnHelpAbout\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnRxID\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnTxID\fP"
.br
.ti -1c
.RI "def \fBOnCmdSliderScroll\fP"
.br
.ti -1c
.RI "def \fBOnSliderScrollBottom\fP"
.br
.ti -1c
.RI "def \fBOnCmdSliderScrollChanged\fP"
.br
.ti -1c
.RI "def \fBOnSliderScrollTop\fP"
.br
.ti -1c
.RI "def \fBOnCheckSQClick\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnOnOff\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnSplitClick\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnAnalogClick\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnALCClick\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnTXClick\fP"
.br
.in -1c