.TH "topFrame.TopFrame" 3 "Mon Sep 10 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
topFrame.TopFrame \- 
.PP
Class \fBTopFrame\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Frame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__del__\fP"
.br
.ti -1c
.RI "def \fBtopFrame_OnClose\fP"
.br
.ti -1c
.RI "def \fBtopFrame_OnPaint\fP"
.br
.ti -1c
.RI "def \fBtopFrame_OnSize\fP"
.br
.ti -1c
.RI "def \fBtopFrame_OnUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnOpen\fP"
.br
.ti -1c
.RI "def \fBOnOpenUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnSave\fP"
.br
.ti -1c
.RI "def \fBOnSaveUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnClose\fP"
.br
.ti -1c
.RI "def \fBOnCloseUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnExit\fP"
.br
.ti -1c
.RI "def \fBOnCopy\fP"
.br
.ti -1c
.RI "def \fBOnCopyUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnCut\fP"
.br
.ti -1c
.RI "def \fBOnCutUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnPaste\fP"
.br
.ti -1c
.RI "def \fBOnPasteUpdateUI\fP"
.br
.ti -1c
.RI "def \fBOnToolsAudio\fP"
.br
.ti -1c
.RI "def \fBOnToolsAudioUI\fP"
.br
.ti -1c
.RI "def \fBOnToolsComCfg\fP"
.br
.ti -1c
.RI "def \fBOnToolsComCfgUI\fP"
.br
.ti -1c
.RI "def \fBOnToolsOptions\fP"
.br
.ti -1c
.RI "def \fBOnToolsOptionsUI\fP"
.br
.ti -1c
.RI "def \fBOnCaptureRxStream\fP"
.br
.ti -1c
.RI "def \fBOnCaptureTxStream\fP"
.br
.ti -1c
.RI "def \fBOnPlayAudioFile\fP"
.br
.ti -1c
.RI "def \fBOnHelpCheckUpdates\fP"
.br
.ti -1c
.RI "def \fBOnHelpCheckUpdatesUI\fP"
.br
.ti -1c
.RI "def \fBOnHelpAbout\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnRxID\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnTxID\fP"
.br
.ti -1c
.RI "def \fBOnCmdSliderScroll\fP"
.br
.ti -1c
.RI "def \fBOnSliderScrollBottom\fP"
.br
.ti -1c
.RI "def \fBOnCmdSliderScrollChanged\fP"
.br
.ti -1c
.RI "def \fBOnSliderScrollTop\fP"
.br
.ti -1c
.RI "def \fBOnCheckSQClick\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnOnOff\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnSplitClick\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnAnalogClick\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnALCClick\fP"
.br
.ti -1c
.RI "def \fBOnTogBtnTXClick\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBm_menubarMain\fP"
.br
.ti -1c
.RI "\fBfile\fP"
.br
.ti -1c
.RI "\fBm_menuItemOpen\fP"
.br
.ti -1c
.RI "\fBm_menuItemSave\fP"
.br
.ti -1c
.RI "\fBm_menuItemClose\fP"
.br
.ti -1c
.RI "\fBm_menuItemExit\fP"
.br
.ti -1c
.RI "\fBedit\fP"
.br
.ti -1c
.RI "\fBm_menuItemCopy\fP"
.br
.ti -1c
.RI "\fBm_menuItemCut\fP"
.br
.ti -1c
.RI "\fBm_menuItemPaste\fP"
.br
.ti -1c
.RI "\fBtools\fP"
.br
.ti -1c
.RI "\fBm_menuItemAudio\fP"
.br
.ti -1c
.RI "\fBm_menuItemRigCtrlCfg\fP"
.br
.ti -1c
.RI "\fBm_menuItemOptions\fP"
.br
.ti -1c
.RI "\fBm_menuItemCaptRxStream\fP"
.br
.ti -1c
.RI "\fBm_menuItemCaptTxStream\fP"
.br
.ti -1c
.RI "\fBm_menuItemPlayAudioFile\fP"
.br
.ti -1c
.RI "\fBhelp\fP"
.br
.ti -1c
.RI "\fBm_menuItemHelpUpdates\fP"
.br
.ti -1c
.RI "\fBm_menuItemAbout\fP"
.br
.ti -1c
.RI "\fBm_gaugeSNR\fP"
.br
.ti -1c
.RI "\fBm_textSNR\fP"
.br
.ti -1c
.RI "\fBm_gaugeLevel\fP"
.br
.ti -1c
.RI "\fBm_auiNbookCtrl\fP"
.br
.ti -1c
.RI "\fBm_txtCtrl\fP"
.br
.ti -1c
.RI "\fBm_togRxID\fP"
.br
.ti -1c
.RI "\fBm_togTxID\fP"
.br
.ti -1c
.RI "\fBm_sliderSQ\fP"
.br
.ti -1c
.RI "\fBm_ckboxSQ\fP"
.br
.ti -1c
.RI "\fBm_togBtnOnOff\fP"
.br
.ti -1c
.RI "\fBm_togBtnSplit\fP"
.br
.ti -1c
.RI "\fBm_togBtnAnalog\fP"
.br
.ti -1c
.RI "\fBm_togBtnALC\fP"
.br
.ti -1c
.RI "\fBm_btnTogTX\fP"
.br
.ti -1c
.RI "\fBm_statusBar1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBTopFrame\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
