.TH "topFrame" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
topFrame \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTopFrame\fP"
.br
.RI "\fIClass \fBTopFrame\fP\&. \fP"
.ti -1c
.RI "class \fBDlgAbout\fP"
.br
.RI "\fIClass \fBDlgAbout\fP\&. \fP"
.ti -1c
.RI "class \fBDlgAudio\fP"
.br
.RI "\fIClass \fBDlgAudio\fP\&. \fP"
.ti -1c
.RI "class \fBDlgOptions\fP"
.br
.RI "\fIClass \fBDlgOptions\fP\&. \fP"
.ti -1c
.RI "class \fBDlgComPorts\fP"
.br
.RI "\fIClass \fBDlgComPorts\fP\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB_\fP gettext\&.gettext"
.br
.ti -1c
.RI "int \fBID_OPEN\fP 1000"
.br
.ti -1c
.RI "int \fBID_SAVE\fP 1001"
.br
.ti -1c
.RI "int \fBID_CLOSE\fP 1002"
.br
.ti -1c
.RI "int \fBID_EXIT\fP 1003"
.br
.ti -1c
.RI "int \fBID_COPY\fP 1004"
.br
.ti -1c
.RI "int \fBID_CUT\fP 1005"
.br
.ti -1c
.RI "int \fBID_PASTE\fP 1006"
.br
.ti -1c
.RI "int \fBID_OPTIONS\fP 1007"
.br
.ti -1c
.RI "int \fBID_ABOUT\fP 1008"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "topFrame\&._ gettext\&.gettext"

.PP
Definition at line 15 of file topFrame\&.py\&.
.SS "int topFrame\&.ID_ABOUT 1008"

.PP
Definition at line 25 of file topFrame\&.py\&.
.SS "int topFrame\&.ID_CLOSE 1002"

.PP
Definition at line 19 of file topFrame\&.py\&.
.SS "int topFrame\&.ID_COPY 1004"

.PP
Definition at line 21 of file topFrame\&.py\&.
.SS "int topFrame\&.ID_CUT 1005"

.PP
Definition at line 22 of file topFrame\&.py\&.
.SS "int topFrame\&.ID_EXIT 1003"

.PP
Definition at line 20 of file topFrame\&.py\&.
.SS "int topFrame\&.ID_OPEN 1000"

.PP
Definition at line 17 of file topFrame\&.py\&.
.SS "int topFrame\&.ID_OPTIONS 1007"

.PP
Definition at line 24 of file topFrame\&.py\&.
.SS "int topFrame\&.ID_PASTE 1006"

.PP
Definition at line 23 of file topFrame\&.py\&.
.SS "int topFrame\&.ID_SAVE 1001"

.PP
Definition at line 18 of file topFrame\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
