.TH "topFrame.DlgAbout" 3 "Mon Sep 10 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
topFrame.DlgAbout \- 
.PP
Class \fBDlgAbout\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Dialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__del__\fP"
.br
.ti -1c
.RI "def \fBOnClose\fP"
.br
.ti -1c
.RI "def \fBOnInitDialog\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBm_bitmapAbout\fP"
.br
.ti -1c
.RI "\fBm_staticText1\fP"
.br
.ti -1c
.RI "\fBm_textCtrl2\fP"
.br
.ti -1c
.RI "\fBm_button9\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBDlgAbout\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
