.TH "C:/bin/Projects/Radio/fdmdv2/src/detritus/topFrame (2).h" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/bin/Projects/Radio/fdmdv2/src/detritus/topFrame (2).h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/artprov\&.h>\fP
.br
\fC#include <wx/xrc/xmlres\&.h>\fP
.br
\fC#include <wx/intl\&.h>\fP
.br
\fC#include <wx/string\&.h>\fP
.br
\fC#include <wx/bitmap\&.h>\fP
.br
\fC#include <wx/image\&.h>\fP
.br
\fC#include <wx/icon\&.h>\fP
.br
\fC#include <wx/menu\&.h>\fP
.br
\fC#include <wx/gdicmn\&.h>\fP
.br
\fC#include <wx/font\&.h>\fP
.br
\fC#include <wx/colour\&.h>\fP
.br
\fC#include <wx/settings\&.h>\fP
.br
\fC#include <wx/gauge\&.h>\fP
.br
\fC#include <wx/textctrl\&.h>\fP
.br
\fC#include <wx/sizer\&.h>\fP
.br
\fC#include <wx/statbox\&.h>\fP
.br
\fC#include <wx/aui/auibook\&.h>\fP
.br
\fC#include <wx/tglbtn\&.h>\fP
.br
\fC#include <wx/slider\&.h>\fP
.br
\fC#include <wx/checkbox\&.h>\fP
.br
\fC#include <wx/statusbr\&.h>\fP
.br
\fC#include <wx/frame\&.h>\fP
.br
\fC#include <wx/statbmp\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include <wx/button\&.h>\fP
.br
\fC#include <wx/dialog\&.h>\fP
.br
\fC#include <wx/radiobut\&.h>\fP
.br
\fC#include <wx/combobox\&.h>\fP
.br
\fC#include <wx/panel\&.h>\fP
.br
\fC#include <wx/listbox\&.h>\fP
.br
\fC#include <wx/notebook\&.h>\fP
.br
\fC#include <wx/listctrl\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTopFrame\fP"
.br
.ti -1c
.RI "class \fBDlgAbout\fP"
.br
.ti -1c
.RI "class \fBDlgAudio\fP"
.br
.ti -1c
.RI "class \fBDlgOptions\fP"
.br
.ti -1c
.RI "class \fBDlgComPorts\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBID_OPEN\fP   1000"
.br
.ti -1c
.RI "#define \fBID_SAVE\fP   1001"
.br
.ti -1c
.RI "#define \fBID_CLOSE\fP   1002"
.br
.ti -1c
.RI "#define \fBID_EXIT\fP   1003"
.br
.ti -1c
.RI "#define \fBID_COPY\fP   1004"
.br
.ti -1c
.RI "#define \fBID_CUT\fP   1005"
.br
.ti -1c
.RI "#define \fBID_PASTE\fP   1006"
.br
.ti -1c
.RI "#define \fBID_OPTIONS\fP   1007"
.br
.ti -1c
.RI "#define \fBID_ABOUT\fP   1008"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ID_ABOUT   1008"

.PP
Definition at line 54 of file topFrame (2)\&.h\&.
.SS "#define ID_CLOSE   1002"

.PP
Definition at line 48 of file topFrame (2)\&.h\&.
.SS "#define ID_COPY   1004"

.PP
Definition at line 50 of file topFrame (2)\&.h\&.
.SS "#define ID_CUT   1005"

.PP
Definition at line 51 of file topFrame (2)\&.h\&.
.SS "#define ID_EXIT   1003"

.PP
Definition at line 49 of file topFrame (2)\&.h\&.
.SS "#define ID_OPEN   1000"

.PP
Definition at line 46 of file topFrame (2)\&.h\&.
.SS "#define ID_OPTIONS   1007"

.PP
Definition at line 53 of file topFrame (2)\&.h\&.
.SS "#define ID_PASTE   1006"

.PP
Definition at line 52 of file topFrame (2)\&.h\&.
.SS "#define ID_SAVE   1001"

.PP
Definition at line 47 of file topFrame (2)\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
