.TH "topFrame.DlgOptions" 3 "Mon Sep 10 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
topFrame.DlgOptions \- 
.PP
Class \fBDlgOptions\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Dialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__del__\fP"
.br
.ti -1c
.RI "def \fBOnClose\fP"
.br
.ti -1c
.RI "def \fBOnInitDialog\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBm_staticText2\fP"
.br
.ti -1c
.RI "\fBm_textCtrl3\fP"
.br
.ti -1c
.RI "\fBm_staticText3\fP"
.br
.ti -1c
.RI "\fBm_textCtrl4\fP"
.br
.ti -1c
.RI "\fBm_staticText4\fP"
.br
.ti -1c
.RI "\fBm_textCtrl5\fP"
.br
.ti -1c
.RI "\fBm_staticText5\fP"
.br
.ti -1c
.RI "\fBm_textCtrl6\fP"
.br
.ti -1c
.RI "\fBm_staticText6\fP"
.br
.ti -1c
.RI "\fBm_textCtrl7\fP"
.br
.ti -1c
.RI "\fBm_staticText7\fP"
.br
.ti -1c
.RI "\fBm_textCtrl8\fP"
.br
.ti -1c
.RI "\fBm_sdbSizer4OK\fP"
.br
.ti -1c
.RI "\fBm_sdbSizer4Cancel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBDlgOptions\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
