.TH "C:/bin/Projects/Radio/fdmdv2/src/topFrame.py" 3 "Tue Oct 16 2012" "Version 02.00.01" "FDMDV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/bin/Projects/Radio/fdmdv2/src/topFrame.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtopFrame\&.TopFrame\fP"
.br
.RI "\fIClass \fBTopFrame\fP\&. \fP"
.ti -1c
.RI "class \fBtopFrame\&.DlgAbout\fP"
.br
.RI "\fIClass \fBDlgAbout\fP\&. \fP"
.ti -1c
.RI "class \fBtopFrame\&.DlgAudio\fP"
.br
.RI "\fIClass \fBDlgAudio\fP\&. \fP"
.ti -1c
.RI "class \fBtopFrame\&.DlgOptions\fP"
.br
.RI "\fIClass \fBDlgOptions\fP\&. \fP"
.ti -1c
.RI "class \fBtopFrame\&.DlgComPorts\fP"
.br
.RI "\fIClass \fBDlgComPorts\fP\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtopFrame\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtopFrame\&._\fP gettext\&.gettext"
.br
.ti -1c
.RI "int \fBtopFrame\&.ID_OPEN\fP 1000"
.br
.ti -1c
.RI "int \fBtopFrame\&.ID_SAVE\fP 1001"
.br
.ti -1c
.RI "int \fBtopFrame\&.ID_CLOSE\fP 1002"
.br
.ti -1c
.RI "int \fBtopFrame\&.ID_EXIT\fP 1003"
.br
.ti -1c
.RI "int \fBtopFrame\&.ID_COPY\fP 1004"
.br
.ti -1c
.RI "int \fBtopFrame\&.ID_CUT\fP 1005"
.br
.ti -1c
.RI "int \fBtopFrame\&.ID_PASTE\fP 1006"
.br
.ti -1c
.RI "int \fBtopFrame\&.ID_OPTIONS\fP 1007"
.br
.ti -1c
.RI "int \fBtopFrame\&.ID_ABOUT\fP 1008"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FDMDV2 from the source code\&.
