//=========================================================================
// Name:          main.h
// Purpose:       Declares simple wxWidgets application with GUI
//                 created using wxFormBuilder.
// Author:
// Created:
// Copyright:
// License:       wxWidgets license (www.wxwidgets.org)
//
// Notes:        Note that all GUI creation code is declared in
//                 gui.h source file which is generated by wxFormBuilder.
//=========================================================================
#ifndef __main__
#define __main__

// main wxWidgets header file
#include <wx/wx.h>
#include <wx/textctrl.h>
#if !defined(__WXMSW__) && !defined(__WXPM__)
    #include "../bitmaps/sample.xpm"
#endif

#ifndef __WXMSW__
    #include "bitmaps/toolbrai.xpm"
    #include "bitmaps/toolchar.xpm"
    #include "bitmaps/tooldata.xpm"
    #include "bitmaps/toolnote.xpm"
    #include "bitmaps/tooltodo.xpm"
    #include "bitmaps/toolchec.xpm"
    #include "bitmaps/toolgame.xpm"
    #include "bitmaps/tooltime.xpm"
    #include "bitmaps/toolword.xpm"
    #include "bitmaps/small1.xpm"
#endif

#define AUDIO_IN      0
#define AUDIO_OUT     1

#define ICON_TRANSPARENT    1
#define ICON_CHECK          0
#define ICON_toolchar       2
#define ICON_tooldata       3
#define ICON_toolgame       4
#define ICON_toolnote       5
#define ICON_TOOLTIME       6
#define ICON_INARROW        7
#define ICON_OUTARROW       8

// gui classes generated by wxFormBuilder
#include "gui.h"
#include "portaudio.h"
#ifdef WIN32
#if PA_USE_ASIO
#include "pa_asio.h"
#endif
#endif


//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=
// application class declaration
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=
class MainApp : public wxApp
{
    public:
        virtual bool OnInit();
};

//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=
// AudioInfoDisplay
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=
class AudioInfoDisplay
{
    public:
        wxListCtrl*     m_listDevices;
        int             direction;
        wxTextCtrl*     m_textDevice;
        wxComboBox*     m_cbSampleRate;
};

// declare global static function wxGetApp()
DECLARE_APP(MainApp)

//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=
// main application frame declaration
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=
class MainFrame : public MainFrameBase
{
    public:
        MainFrame( wxWindow *parent );
        virtual ~MainFrame();
        PaError         pa_err;
        bool            m_isPaInitialized;
        wxImageList     *m_imageListNormal;
        wxImageList     *m_imageListSmall;

    protected:
        // protected event handlers
        void OnCloseFrame( wxCloseEvent& event );
        void OnDeviceSelect( wxListEvent& event );

        void OnExitClick( wxCommandEvent& event );
        void OnRefreshClick( wxCommandEvent& event );
        void DisplaySupportedSampleRates(const PaStreamParameters *inputParameters, const PaStreamParameters *outputParameters);
        void populateParams(AudioInfoDisplay);
        void showAPIInfo();
        AudioInfoDisplay m_RxInDevices;
        AudioInfoDisplay m_RxOutDevices;
        AudioInfoDisplay m_TxInDevices;
        AudioInfoDisplay m_TxOutDevices;
};

#endif //__main__
