/*********************************************************************
 * Name:          main.h
 * Purpose:       Declares simple wxWidgets application with GUI
 *                 created using wxFormBuilder.
 * Author:
 * Created:
 * Copyright:
 * License:       wxWidgets license (www.wxwidgets.org)
 *
 * Notes:        Note that all GUI creation code is declared in
 *                 gui.h source file which is generated by wxFormBuilder.
 *********************************************************************/

#ifndef __main__
#define __main__

// main wxWidgets header file
#include <wx/wx.h>

// Necessary Audio Stuff
#include "../libsndfile/include/sndfile.h"
#include "../extern/include/portaudio.h"
#include "../extern/include/portaudiocpp/PortAudioCpp.hxx"
#ifdef WIN32
#include "../extern/include/portaudiocpp/AsioDeviceAdapter.hxx"
#endif
#include "paclass.h"

// Fdmdv2 & Codec2 stuff
#include "C:\Users\wittend\Projects\Radio\codec2-dev\src\codec2.h"
#include "C:\Users\wittend\Projects\Radio\codec2-dev\src\fdmdv.h"

// gui classes generated by wxFormBuilder
#include "gui.h"

////////////////////////////////////////////////////////////////////////////////
// application class declaration
////////////////////////////////////////////////////////////////////////////////

class MainApp : public wxApp
{
    public:
        virtual bool OnInit();
};

// declare global static function wxGetApp()
DECLARE_APP(MainApp)

////////////////////////////////////////////////////////////////////////////////
// main application frame declaration
////////////////////////////////////////////////////////////////////////////////

class MainDialog : public MainDialogBase
{
    public:
        MainDialog( wxWindow *parent );
        virtual ~MainDialog();
        bool            m_RxRunning;
        bool            m_TxRunning;
        CODEC2          *m_RXCodec2;
        CODEC2          *m_TXCodec2;
        PortAudioWrap   *m_rxPa;
        PortAudioWrap   *m_txPa;
        PaDeviceIndex   m_rxDevIn;
        PaDeviceIndex   m_rxDevOut;
        PaDeviceIndex   m_txDevIn;
        PaDeviceIndex   m_txDevOut;
        PaError         m_rxErr;
        PaError         m_txErr;

    protected:
        // protected event handlers
        void startTxStream();
        void startRxStream();
        void stopTxStream();
        void stopRxStream();
        void abortTxStream();
        void abortRxStream();
        void OnInitDialog( wxInitDialogEvent& event );
        void OnCloseDialog( wxCloseEvent& event );
        void OnOKClick( wxCommandEvent& event );
        void OnCancelClick( wxCommandEvent& event );
        void OnToggleStartStop( wxCommandEvent& event );
        void OnToggleRxRx( wxCommandEvent& event );
        void OnRxInSelect( wxCommandEvent& event );
        void OnRxOutSelect( wxCommandEvent& event );
        void OnTxInSelect( wxCommandEvent& event );
        void OnTxOutSelect( wxCommandEvent& event );
        void OnRadioSelect( wxCommandEvent& event );
        void OnPortSelect( wxCommandEvent& event );

        void populateStandardSampleRates(wxComboBox* target, const portaudio::DirectionSpecificStreamParameters &inputParameters, const portaudio::DirectionSpecificStreamParameters &outputParameters);
        int populateAudioInfo();

};

#endif //__main__
